variables:
- group: wayland

jobs:
  # Test jobs below this point
  - job: test_windows
    displayName: "Test Windows"
    pool:
      name: test-pool-onv12-1
      demands: Agent.OS -equals Windows_NT
    steps:
      - bash: |
          echo "HOME: $HOME"
          echo $GITHUB_TOKEN
          git clone https://$GITHUB_TOKEN@github.com/NordicPlayground/nrf-device-lib
        env:
          GITHUB_TOKEN: $(WAYLAND_GITHUB_TOKEN)
  - job: test_darwin
    displayName: "Test macOS"
    pool:
      name: test-pool-onv12-1
      demands: Agent.OS -equals Darwin
    steps:
      - bash: |
          echo "HOME: $HOME"
          echo $GITHUB_TOKEN
          git clone https://$GITHUB_TOKEN@github.com/NordicPlayground/nrf-device-lib
          md5sum token
        env:
          GITHUB_TOKEN: $(WAYLAND_GITHUB_TOKEN)
