variables:
- group: wayland
- name: VCPKG_EXPORT_FILENAME
  value: 'vcpkg-export-$(vcpkg_triplet)-$(Build.BuildNumber)'

jobs:
  - job: test_windows
    displayName: "Test Windows"
    pool:
      vmImage: vs2017-win2016
    steps:
      - bash: |
          unzip --help
          echo "ASDF: $(Build.SourcesDirectory)"
          cygpath -u "$(Build.SourcesDirectory)"
          ls `cygpath -u "$(Build.SourcesDirectory)"`
      - script: |
          echo "%VCPKG_EXPORT_FILENAME%"
      - template: 'prepare-vcpkg.yaml'
        parameters:
          triplet: 'x64-linux'
      - template: 'prepare-vcpkg.yaml'
        parameters:
          triplet: 'x64-osx'
      - template: 'prepare-vcpkg.yaml'
        parameters:
          triplet: 'x86-windows'
      - template: 'prepare-vcpkg.yaml'
        parameters:
          triplet: 'x64-windows'

#  - job: test_darwin
#    displayName: "Test macOS"
#    pool:
#      name: test-pool-onv12-1
#      demands: Agent.OS -equals Darwin
#    steps:
#      - bash: |
#          echo "HOME: $HOME"
#          echo "$GITHUB_TOKEN"
#          echo "$KEN_TEST"
#          echo "$NORDIC_DEVELOPER_USER"
#          git clone https://kenr:$GITHUB_TOKEN@github.com/NordicPlayground/nrf-device-lib
#        env:
#          GITHUB_TOKEN: $(KEN_TEST)
#
##
# platform: Darwin-x64 | Linux-x64 | Windows
#
