parameters:
  - name: node_versions
    displayName: Node versions
    type: object
    default:
      - 14.9.0
      - 12.18.3
      - 12.17.0
      - 12.16.3
      - 12.15.0
      - 12.14.1
      - 12.13.1
      - 12.13.0
      - 12.12.0
      - 12.11.1
      - 12.10.0
      - 12.9.1
      - 12.8.1
      - 12.7.0
      - 12.6.0
      - 12.5.0
  - name: test_pool
    displayName: Test pool
    default: test-pool-onv12-1
    values:
      - test-pool-onv12-1

variables:
  system.debug: true

jobs:
  - job: build_binding
    displayName: "Build binding"
    steps:
      - bash: |
          echo "How are you all doing? Ready to test?"
  - job: test_win86
    displayName: "Test win32"
    dependsOn: "build_binding"
    pool:
      name: ${{ parameters.test_pool }}
      demands: Agent.OS -equals Windows_NT
    steps:
      - template: cool-jobs.yaml
        parameters:
          architecture: x86
          agent_os: Windows_NT
          node_arch: 32
          node_versions: ${{ parameters.node_versions }}
  - job: test_win64
    displayName: "Test win64"
    dependsOn: "build_binding"
    pool:
      name: ${{ parameters.test_pool }}
      demands: Agent.OS -equals Windows_NT
    steps:
      - template: cool-jobs.yaml
        parameters:
          architecture: x64
          agent_os: Windows_NT
          node_arch: 64
          node_versions: ${{ parameters.node_versions }}
  - job: test_macos
    displayName: "Test macOS"
    dependsOn: "build_binding"
    pool:
      name: ${{ parameters.test_pool }}
      demands: Agent.OS -equals Darwin
    steps:
      - template: cool-jobs.yaml
        parameters:
          architecture: x64
          agent_os: Darwin
          node_arch: 64
          node_versions: ${{ parameters.node_versions }}
  - job: test_linux
    displayName: "Test Linux"
    dependsOn: "build_binding"
    pool:
      name: ${{ parameters.test_pool }}
      demands: Agent.OS -equals Linux
    steps:
      - template: cool-jobs.yaml
        parameters:
          architecture: x64
          agent_os: Linux
          node_arch: 64
          node_versions: ${{ parameters.node_versions }}
