variables:
- group: wayland

jobs:
  # Test jobs below this point
  - job: test_windows
    displayName: "Test Windows"
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: 'prepare-vcpkg.yaml'
        parameters:
          platform: 'Darwin-x64'
      - bash: |
          echo "Hello world!"
#  - job: test_darwin
#    displayName: "Test macOS"
#    pool:
#      name: test-pool-onv12-1
#      demands: Agent.OS -equals Darwin
#    steps:
#      - bash: |
#          echo "HOME: $HOME"
#          echo "$GITHUB_TOKEN"
#          echo "$KEN_TEST"
#          echo "$NORDIC_DEVELOPER_USER"
#          git clone https://kenr:$GITHUB_TOKEN@github.com/NordicPlayground/nrf-device-lib
#        env:
#          GITHUB_TOKEN: $(KEN_TEST)
#
##
# platform: Darwin-x64 | Linux-x64 | Windows
#   