variables:
- group: wayland
- name: WAYLAND_GITHUB_TOKEN
  value: $[variables.WAYLAND_GITHUB_TOKEN] # uses runtime expression

jobs:
  # Test jobs below this point
  - job: test_windows
    displayName: "Test Windows"
    pool:
      name: test-pool-onv12-1
      demands: Agent.OS -equals Windows_NT
    steps:
      - bash: |
          echo "HOME: $HOME"
          echo "WAYLAND_GITHUB_TOKEN: $(WAYLAND_GITHUB_TOKEN)"
  - job: test_darwin
    displayName: "Test macOS"
    pool:
      name: test-pool-onv12-1
      demands: Agent.OS -equals Darwin
    steps:
      - bash: |
          echo "HOME: $HOME"
          echo "WAYLAND_GITHUB_TOKEN: $(WAYLAND_GITHUB_TOKEN)"
