parameters:
  - name: WINDOWS_IMAGE
    displayName: Windows image
    type: string
    default: vs2017-win2016
    values:
      - windows-latest
      - windows-2019
      - vs2017-win2016
  - name: MACOS_IMAGE
    displayName: macOS image
    type: string
    default: macOS-10.15
    values:
      - macOS-latest
      - macOS-10.15
      - macOS-10.14
  - name: LINUX_IMAGE
    displayName: Linux image
    type: string
    default: ubuntu-18.04
    values:
      - ubuntu-latest
      - ubuntu-18.04
      - ubuntu-16.04

variables:
  system.debug: true
  template: nodejs-versions.yaml

jobs:
  # Test jobs below this point
  - job: test_linux64
    displayName: "Test Linux"
    pool:
      name: test-pool-onv12-1
      demands: Agent.OS -equals Linux
    steps:
      - ${{ each node_version in parameters.node_versions }}:
        - template: nodejs-steps.yaml
          parameters:
            node_version: ${{ variables.node_version }}
