parameters:
  - name: node_versions
    displayName: Node versions
    type: object
    default:
      - 14.9.0
      - 14.8.0
      - 14.7.0
      - 14.6.0
      - 14.10.1
      - 14.10.0
      - 14.9.0
      - 14.8.0
      - 14.7.0
      - 14.6.0
      - 14.5.0
      - 14.4.0
      - 14.3.0
      - 14.2.0
      - 14.1.0
      - 14.0.0
      - 13.14.0
      - 13.13.0
      - 13.12.0
      - 13.11.0
      - 13.10.1
      - 13.10.0
      - 13.9.0
      - 13.8.0
      - 13.7.0
      - 13.6.0
      - 13.5.0
      - 13.4.0
      - 13.3.0
      - 13.2.0
      - 13.1.0
      - 13.0.1
      - 13.0.0
      - 12.18.3
      - 12.18.2
      - 12.18.1
      - 12.18.0
      - 12.17.0
      - 12.16.3
      - 12.16.2
      - 12.16.1
      - 12.16.0
      - 12.15.0
      - 12.14.1
      - 12.14.0
      - 12.13.1
      - 12.13.0
      - 12.12.0
      - 12.11.1
      - 12.11.0
      - 12.10.0
      - 12.9.1
      - 12.9.0
      - 12.8.1
      - 12.8.0
      - 12.7.0
      - 12.6.0
      - 12.5.0
      - 12.4.0
      - 12.3.1
      - 12.3.0
      - 12.2.0
      - 12.1.0
      - 12.0.0
      - 11.15.0
      - 11.14.0
      - 11.13.0
      - 11.12.0
      - 11.11.0
      - 11.10.1
      - 11.10.0
      - 11.9.0
      - 11.8.0
      - 11.7.0
      - 11.6.0
      - 11.5.0
      - 11.4.0
      - 11.3.0
      - 11.2.0
      - 11.1.0
      - 11.0.0
      - 10.22.0
      - 10.21.0
      - 10.20.1
      - 10.20.0
      - 10.19.0
      - 10.18.1
      - 10.18.0
      - 10.17.0
      - 10.16.3
      - 10.16.2
      - 10.16.1
      - 10.16.0
      - 10.15.3
      - 10.15.2
      - 10.15.1
      - 10.15.0
      - 10.14.2
      - 10.14.1
      - 10.14.0
      - 10.13.0
      - 10.12.0
      - 10.11.0
      - 10.10.0
      - 10.9.0
      - 10.8.0
      - 10.7.0
      - 10.6.0
      - 10.5.0
      - 10.4.1
      - 10.4.0
      - 10.3.0
      - 10.2.1
      - 10.2.0
      - 10.1.0
      - 10.0.0
      - 9.11.2
      - 9.11.1
      - 9.11.0
      - 9.10.1
      - 9.10.0
      - 9.9.0
      - 9.8.0
      - 9.7.1
      - 9.7.0
      - 9.6.1
      - 9.6.0
      - 9.5.0
      - 9.4.0
      - 9.3.0
      - 9.2.1
      - 9.2.0
      - 9.1.0
      - 9.0.0
      - 8.17.0
      - 8.16.2
      - 8.16.1
      - 8.16.0
      - 8.15.1
      - 8.15.0
      - 8.14.1
      - 8.14.0
      - 8.13.0
      - 8.12.0
      - 8.11.4
      - 8.11.3
      - 8.11.2
      - 8.11.1
      - 8.11.0
      - 8.10.0
      - 8.9.4
      - 8.9.3
      - 8.9.2
      - 8.9.1
      - 8.9.0
      - 8.8.1
      - 8.8.0
      - 8.7.0
      - 8.6.0
      - 8.5.0
      - 8.4.0
      - 8.3.0
      - 8.2.1
      - 8.2.0
      - 8.1.4
      - 8.1.3
      - 8.1.2
      - 8.1.1
      - 8.1.0
      - 8.0.0
  - name: node_arch_Windows_NT
    displayName: Node versions
    type: object
    default:
      - 32
      - 64
  - name: node_arch_Linux
    displayName: Node versions
    type: object
    default:
      - 64
  - name: node_arch_Darwin
    displayName: Node versions
    type: object
    default:
      - 64
  - name: test_pool
    displayName: Test pool
    default: test-pool-onv12-1
    values:
      - test-pool-onv12-1
  - name: agents
    displayName: Agents
    type: object
    default:
      Windows_NT
      Darwin
      Linux

variables:
  system.debug: true

jobs:
  - job: build_binding
    displayName: "Build binding"
    steps:
      - bash: |
          echo "How are you all doing?"

  - job: test_win86
    displayName: "Test win32"
    dependsOn: "build_binding"
    pool:
      name: test-pool-onv12-1
      demands: Agent.OS -equals Windows_NT
    steps:
      - template: cool-jobs.yaml
        parameters:
          architecture: x86
          agent_os: Windows_NT
          node_arch: 32
  - job: test_win64
    displayName: "Test win64"
    dependsOn: "build_binding"
    pool:
      name: test-pool-onv12-1
      demands: Agent.OS -equals Windows_NT
    steps:
      - template: cool-jobs.yaml
        parameters:
          architecture: x64
          agent_os: Windows_NT
          node_arch: 64
          node_versions: ${{ parameters.node_versions }}
