parameters:
  - name: WINDOWS_IMAGE
    displayName: Windows image
    type: string
    default: vs2017-win2016
    values:
      - windows-latest
      - windows-2019
      - vs2017-win2016
  - name: MACOS_IMAGE
    displayName: macOS image
    type: string
    default: macOS-10.15
    values:
      - macOS-latest
      - macOS-10.15
      - macOS-10.14
  - name: LINUX_IMAGE
    displayName: Linux image
    type: string
    default: ubuntu-18.04
    values:
      - ubuntu-latest
      - ubuntu-18.04
      - ubuntu-16.04

variables:
  system.debug: true

resources:
  repositories:
    - repository: .azure-common
      type: github
      endpoint: kenr-githubconnection
      name: kenr/js-common

steps:
  - checkout: self
  - checkout: .azure-common

extends:
  template: .azure-common/supported-nodejs-versions.yml

jobs:
  # Test jobs below this point
  - job: test_windows
    displayName: "Test Windows"
    pool:
      name: test-pool-onv12-1
      demands: Agent.OS -equals Windows_NT
    steps:
      - ${{ each node_version in parameters.node_versions }}:
        - ${{ each node_arch in parameters.node_arch_Windows_NT }}:
          - template: setup-nodejs.yaml
            parameters:
              node_version: ${{ node_version }}
              node_arch: ${{ node_arch }}
          - bash: |
              node -e "console.log(process.version+\" arch:\"+process.arch)"
  - job: test_darwin
    displayName: "Test macOS"
    pool:
      name: test-pool-onv12-1
      demands: Agent.OS -equals Darwin
    steps:
      - ${{ each node_version in parameters.node_versions }}:
        - ${{ each node_arch in parameters.node_arch_Darwin }}:
          - template: setup-nodejs.yaml
            parameters:
              node_version: ${{ node_version }}
              node_arch: ${{ node_arch }}
          - bash: |
              node -e "console.log(process.version+\" arch:\"+process.arch)"
            displayName: Print nodejs version and arch
