trigger:
  - master

parameters:
  - name: WINDOWS_IMAGE
    displayName: Windows image
    type: string
    default: vs2017-win2016
    values:
      - windows-latest
      - windows-2019
      - vs2017-win2016
  - name: MACOS_IMAGE
    displayName: macOS image
    type: string
    default: macOS-10.15
    values:
      - macOS-latest
      - macOS-10.15
      - macOS-10.14
  - name: LINUX_IMAGE
    displayName: Linux image
    type: string
    default: ubuntu-18.04
    values:
      - ubuntu-latest
      - ubuntu-18.04
      - ubuntu-16.04

variables:
  system.debug: true
  node_version: 13.12.0

jobs:
  # Test jobs below this point
  - job: test_linux64
    displayName: "Test Linux"
    pool:
      name: test-pool-onv12-1
      demands: Agent.OS -equals Linux
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
      - script: node --version

  - job: test_macos
    displayName: "Test macOS"
    pool:
      name: test-pool-onv12-1
      demands: Agent.OS -equals Darwin
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
      - script: node --version

  - job: test_win86
    displayName: "Test win32"
    pool:
      name: test-pool-onv12-1
      demands: Agent.OS -equals Windows_NT
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
      - script: node --version

  - job: test_win64
    displayName: "Test win64"
    pool:
      name: test-pool-onv12-1
      demands: Agent.OS -equals Windows_NT
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
      - script: node --version
