variables:
- group: wayland
- name: VCPKG_EXPORT_FILENAME
  value: 'vcpkg-export-$(vcpkg_triplet)-$(Build.BuildNumber)'

jobs:
  - job: test
    displayName: "Test"
    pool:
      vmImage: macOS-10.15
    steps:
      - bash: |
          echo "You silly cow!" > file.txt
          brew install openssl@1.1
          openssl version -a

          export PATH="/usr/local/opt/openssl/bin:$PATH" # This is just for macOS
          ls -la "/usr/local/opt/"
          openssl enc -aes-256-cbc -salt -pbkdf2 -in file.txt -out file.txt.enc -k mae7EiT8
      - bash: |
          export PATH="/usr/local/opt/openssl/bin:$PATH" # This is just for macOS
          openssl enc -aes-256-cbc -d -pbkdf2 -in file.txt.enc -out file-output.txt -k ASDF
          cat file-output.txt
      - template: 'prepare-vcpkg.yaml'
        parameters:
          TRIPLET: 'x64-linux'
          VCPKG_ROOT: "$(Build.SourcesDirectory)/vcpkg"
          ARTIFACT_DIRECTORY: "$(Build.SourcesDirectory)/temp"
      - template: 'prepare-vcpkg.yaml'
        parameters:
          TRIPLET: 'x64-osx'
          VCPKG_ROOT: "$(Build.SourcesDirectory)/vcpkg"
          ARTIFACT_DIRECTORY: "$(Build.SourcesDirectory)/temp"
      - template: 'prepare-vcpkg.yaml'
        parameters:
          TRIPLET: 'x86-windows'
          VCPKG_ROOT: "$(Build.SourcesDirectory)/vcpkg"
          ARTIFACT_DIRECTORY: "$(Build.SourcesDirectory)/temp"
      - template: 'prepare-vcpkg.yaml'
        parameters:
          TRIPLET: 'x64-windows'
          VCPKG_ROOT: "$(Build.SourcesDirectory)/vcpkg"
          ARTIFACT_DIRECTORY: "$(Build.SourcesDirectory)/temp"
