variables:
- group: wayland

jobs:
  # Test jobs below this point
  - job: test_windows
    displayName: "Test Windows"
    pool:
      name: test-pool-onv12-1
      demands: Agent.OS -equals Windows_NT
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          source: 'specific'
          project: 'Wayland'
          pipeline: 'NordicPlayground.vcpkg-export'
          artifact: 'vcpkg-export-Darwin-x64'
          path: $(Build.SourcesDirectory)/bin
          runVersion: 'specific'
          runId: 5934
      - bash: |
          echo "$GITHUB_TOKEN" > token

          echo "HOME: $HOME"
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
          echo "NORDIC_DEVELOPER_USER: $NORDIC_DEVELOPER_USER"
          echo ""
          mkdir x
          cd x
          git clone https://waylandCI:$GITHUB_TOKEN@github.com/NordicPlayground/nrf-device-lib
          cd nrf-device-lib
          git status
          cd ../..
          mkdir y
          cd y
          git clone https://$GITHUB_TOKEN@github.com/NordicPlayground/nrf-device-lib
          cd nrf-device-lib
          git status
          cd ../..
          curl -L -H "Authorization: token $GITHUB_TOKEN" https://github.com/NordicPlayground/nrf-device-lib/archive/master.tar.gz
        env:
          GITHUB_TOKEN: $(WAYLAND_GITHUB_PRIVATE_TOKEN)
#  - job: test_darwin
#    displayName: "Test macOS"
#    pool:
#      name: test-pool-onv12-1
#      demands: Agent.OS -equals Darwin
#    steps:
#      - bash: |
#          echo "HOME: $HOME"
#          echo "$GITHUB_TOKEN"
#          echo "$KEN_TEST"
#          echo "$NORDIC_DEVELOPER_USER"
#          git clone https://kenr:$GITHUB_TOKEN@github.com/NordicPlayground/nrf-device-lib
#        env:
#          GITHUB_TOKEN: $(KEN_TEST)
